
services:
  # Eureka Discovery Server (has to be started first)
  discovery-server:
    build: ./spring-petclinic-discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - petclinic-network

  # Config Server (central configuration server)
  config-server:
    build: ./spring-petclinic-config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - petclinic-network

  # API Gateway
  api-gateway:
    build: ./spring-petclinic-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    depends_on:
      - config-server
      - discovery-server
      - customers-service
      - visits-service
      - vets-service
    networks:
      - petclinic-network

  # Customers Service
  customers-service:
    build: ./spring-petclinic-customers-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    depends_on:
      - config-server
      - discovery-server
    networks:
      - petclinic-network

  # Visits Service
  visits-service:
    build: ./spring-petclinic-visits-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    depends_on:
      - config-server
      - discovery-server
    networks:
      - petclinic-network

  # Vets Service
  vets-service:
    build: ./spring-petclinic-vets-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    depends_on:
      - config-server
      - discovery-server
    networks:
      - petclinic-network

  # Admin Server
  admin-server:
    build: ./spring-petclinic-admin-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka
    depends_on:
      - discovery-server
      - config-server
    networks:
      - petclinic-network

networks:
  petclinic-network:
    driver: bridge
