# spring-petclinic-vets-service/src/main/resources/application.yml

spring:
  application:
    name: vets-service
  profiles:
    active: docker
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  cache:
    cache-names: vets
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka}

# Prometheus configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/vets?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
