spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  profiles:
    active: mysql
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # ddl-auto: validate
      ddl-auto: uodate
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: never
      # mode: always
      # schema-locations: classpath:db/mysql/schema.sql
      # data-locations: classpath:db/mysql/data.sql
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://admin-server:9090}
        instance:
          prefer-ip: true

server:
  port: ${SERVER_PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka}
  instance:
    hostname: vets-service
    prefer-ip-address: false

# Configuration des métriques Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

# Désactivation de Zipkin par défaut  
  tracing:
    enabled: false
    zipkin:
      endpoint: ""
