# spring-petclinic-vets-service/src/main/resources/application.yml

spring:
  application:
    name: vets-service
  profiles:
    active: docker
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  cache:
    cache-names: vets
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
