apiVersion: v1
kind: Service
metadata:
  name: {{ include "discovery-server.fullname" . }}    # Nom du service exposé
  labels:
    app: {{ include "discovery-server.name" . }}      # Cible les pods avec ce label
  annotations:
    prometheus.io/scrape: "true"                      # Autorise Prometheus à collecter les métriques
    prometheus.io/path: "/actuator/prometheus"        # Point d'accès aux métriques Spring Boot
    prometheus.io/port: "8761"                        # Port exposé pour les métriques
spec:
  type: {{ .Values.service.type }}                    # Type de service (ClusterIP, NodePort, etc.)
  selector:
    app: {{ include "discovery-server.name" . }}      # Sélectionne les pods par label
  ports:
    - name: http                                      # Prenom du port HTTP
      protocol: TCP
      port: {{ .Values.service.port }}                # Port dans Kubernetes
      targetPort: {{ .Values.containerPort }}         # Port dans le conteneur
