apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockerhub-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: dockerhub-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: dockerhub-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: dockerhub-credentials
        property: password
    - secretKey: sonarqube_token
      remoteRef:
        key: dockerhub-credentials
        property: sonarqube_token
    - secretKey: test_domain
      remoteRef:
        key: dockerhub-credentials
        property: test_domain
    - secretKey: ecrRepository
      remoteRef:
        key: dockerhub-credentials
        property: ecrRepository
    - secretKey: certificateArn
      remoteRef:
        key: dockerhub-credentials
        property: certificateArn
    - secretKey: domainName
      remoteRef:
        key: dockerhub-credentials
        property: domainName
    - secretKey: db_host
      remoteRef:
        key: dockerhub-credentials
        property: db_host
    - secretKey: db_user
      remoteRef:
        key: dockerhub-credentials  
        property: db_user
    - secretKey: db_password
      remoteRef:
        key: dockerhub-credentials
        property: db_password
    - secretKey: db_name
      remoteRef:
        key: dockerhub-credentials
        property: db_name
