version: 0.2

phases:
  install:
    commands:
      - echo "installation de kubectl et helm..."
      - ARCH=$(uname -m)
      - if [ "$ARCH" = "aarch64" ]; then PLATFORM="arm64"; else PLATFORM="amd64"; fi
      - curl -LO "https://dl.k8s.io/release/v1.27.2/bin/linux/${PLATFORM}/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
      - curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - echo "mise à jour du kubeconfig pour le cluster eks..."
      - aws sts get-caller-identity
      - echo "Current ROLE_ARN is [$ROLE_ARN]"
      - aws eks update-kubeconfig --region $AWS_REGION --name petclinic-cluster --role-arn $ROLE_ARN
      - export KUBECONFIG=/root/.kube/config

  pre_build:
    commands:
      - echo "vérification de la version de helm..."
      - helm version
      - echo "vérification d'accès au cluster..."
      - kubectl get nodes
      - echo "Si l'accès est refusé, vérifiez que AWS::EKS::AccessEntry est correctement configuré"

  build:
    commands:
      - echo "génération des templates helm..."
      - helm template ${SERVICE_NAME} ${HELM_CHART_PATH} --namespace default --set image.tag=latest --set imagePullSecret.dockerconfigjson="" > output.yaml
      - echo "application des manifests sur eks..."
      - kubectl apply -f output.yaml

artifacts:
  files:
    - '**/*'
  name: deploy-artifacts