version: 0.2

phases:
  install:
    commands:
      - echo Installing kubectl and helm...
      - curl -o kubectl https://amazon-eks.s3.eu-west-3.amazonaws.com/1.27.2/2023-10-05/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/
      - curl -sSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - echo Updating kubeconfig for EKS cluster...
      - aws eks update-kubeconfig --region $AWS_REGION --name petclinic-cluster
      - export KUBECONFIG=/root/.kube/config

  pre_build:
    commands:
      - echo Checking helm version...
      - helm version

  build:
    commands:
      - echo Deploying ${SERVICE_NAME} to EKS with Helm...
      - helm upgrade --install ${SERVICE_NAME} ${HELM_CHART_PATH} --namespace default --set image.tag=latest

artifacts:
  files:
    - '**/*'
  name: deploy-artifacts
