# spring-petclinic-api-gateway/src/main/resources/application.yml
server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://admin-server:9091}
        instance:
          prefer-ip: true
  
  # Configuration Spring Cloud Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: vets-service  
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

# Configuration Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: api-gateway
    prefer-ip-address: false
    non-secure-port: 8080

# Configuration des metriques Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  # Desactivation complete de Zipkin et tracing
  tracing:
    enabled: false
  zipkin:
    tracing:
      endpoint: ""
    
# Desactivation Zipkin au niveau Spring Boot
  sleuth:
    enabled: false
    zipkin:
      enabled: false

# Logging pour debug
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
    zipkin2: OFF
    brave: OFF