# spring-petclinic-visits-service/src/main/resources/application.yml

spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://discovery-server:8761/eureka}

server:
  port: 8083

spring.boot.admin.client.url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://admin-server:9090}
spring.boot.admin.client.instance.prefer-ip: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true