apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway.fullname" . }}  # nom du déploiement basé sur release + chart
spec:
  replicas: {{ .Values.replicaCount }}          # nombre de pods souhaités
  selector:
    matchLabels:
      app: {{ include "api-gateway.name" . }}   # utilisé pour associer les pods à ce déploiement
  template:
    metadata:
      labels:
        app: {{ include "api-gateway.name" . }} # label utilisé pour le service
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  # image Docker à déployer
          ports:
            - containerPort: {{ .Values.containerPort }}                   # port exposé dans le container
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profiles.active | quote }}          # profil Spring actif (ex: docker)
