apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}    # nom du service exposé
spec:
  type: {{ .Values.service.type }}                # type de service (ClusterIP, NodePort, etc.)
  selector:
    app: {{ include "api-gateway.name" . }}       # cible les pods avec ce label
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}            # port du service exposé
      targetPort: {{ .Values.containerPort }}     # port interne dans le container
