spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://config-server:8888
  profiles:
    active: default

# Réduction des logs inutiles au démarrage
logging:
  level:
    org:
      springframework:
        boot: INFO
        web: INFO

# Profil par défaut pour exécution en local
---
spring:
  config:
    activate:
      on-profile: default
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

server:
  port: 8761

# Profil utilisé en mode docker-compose
---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: discovery-server
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

server:
  port: 8761
