apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "customers-service.fullname" . }}
  labels:
    app: {{ include "customers-service.name" . }}
    release: monitoring
spec:
  selector:
    matchLabels:
      app: {{ include "customers-service.name" . }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
