spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}
  profiles:
    active: mysql
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoCommit=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    hikari:
      auto-commit: false
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1200000
      maximum-pool-size: 5
      minimum-idle: 1
      pool-name: SpringBootJPAHikariCP
      leak-detection-threshold: 60000
      initialization-fail-timeout: 30000
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          provider_disables_autocommit: true
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        format_sql: false
        use_sql_comments: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/mysql/schema.sql
      data-locations: classpath:db/mysql/data.sql
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://admin-server:9090}
        instance:
          prefer-ip: ${SPRING_BOOT_ADMIN_CLIENT_PREFER_IP:true}

server:
  port: ${SERVER_PORT:8081}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:customers-service}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,readiness
  endpoint:
    health:
      show-details: always
      db:
        enabled: true
    readiness:
      enabled: true
    prometheus:
      enabled: true
  health:
    db:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.samples.petclinic.customers: INFO
    com.zaxxer.hikari: INFO
    org.springframework.jdbc: WARN
    org.hibernate.SQL: false
    root: INFO