replicaCount: 1                         # Nombre de pods (réplicas)

image:
  repository: api-gateway         # Nom logique de l'image (sera remplacé par le repo ECR via le fichier secret)
  tag: latest                           # Tag de l’image Docker

containerPort: 8080                     # Port exposé par le conteneur

service:
  type: ClusterIP                       # Type de service Kubernetes
  port: 80                              # Port du service exposé aux autres pods

spring:
  profiles:
    active: docker                      # Profil Spring actif

metrics:
  serviceMonitor:
    enabled: true
    interval: 15s
    scrapeTimeout: 10s
    additionalLabels:
      release: prometheus
