{{- if .Values.imagePullSecret.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admin-server.fullname" . }}-ecr-auth
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.imagePullSecret.dockerconfigjson | quote }}
{{- end }}
