apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials-secret
  namespace: default
type: Opaque
stringData:
  access-key-id: {{ .Values.awsAccessKeyId }}
  secret-access-key: {{ .Values.awsSecretAccessKey }}
