AWSTemplateFormatVersion: "2010-09-09"
Description: "RDS MySQL for Petclinic"

Parameters:
  DBInstanceIdentifier:
    Type: String
    Default: "petclinic-db"
  DBName:
    Type: String
    Default: "petclinic"
  DBInstanceClass:
    Type: String
    Default: "db.t3.micro"
  VPCSecurityGroupId:
    Type: String
  VPCId:
    Type: String
  DBSubnetIds:
    Type: CommaDelimitedList

Resources:
  MyDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for RDS"
      SubnetIds: !Ref DBSubnetIds

  MyDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      AllocatedStorage: 20
      DBInstanceClass: !Ref DBInstanceClass
      Engine: mysql
      EngineVersion: "8.0"
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      DBName: !Ref DBName
      VPCSecurityGroups:
        - !Ref VPCSecurityGroupId
      DBSubnetGroupName: !Ref MyDBSubnetGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 0

Outputs:
  RDSInstanceEndpoint:
    Value: !GetAtt MyDBInstance.Endpoint.Address
