apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-server.fullname" . }}  # Nom du service exposé
  labels:
    app: {{ include "config-server.name" . }}    # Label utilisé pour le service
spec:
  type: {{ .Values.service.type }}                    # Type de service (ClusterIP, NodePort, etc.)
  selector:
    app: {{ include "config-server.name" . }}     # Cible les pods avec ce label
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}                # Port du service (ex: 8888)
      targetPort: {{ .Values.containerPort }}         # Port interne dans le container
      name: http                                # Nom du port (ex: http)