# configuration pour le déploiement local dans minikube
containerPort: 8080
image:
  repository: admin-server
  tag: latest
  pullPolicy: Never
service:
  port: 8080
  portName: http
serviceMonitor:
  enabled: true
  path: /actuator/prometheus
  port: http
  interval: 15s
  scrapeTimeout: 10s
  additionalLabels:
    release: monitoring
